name: app
description: moneysup app

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_riverpod: ^2.4.0
  hooks_riverpod: ^2.4.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.6

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  fonts:
    - family: Onest
      fonts:
        - asset: assets/fonts/OnestLight.ttf
          weight: 300
        - asset: assets/fonts/OnestRegular.ttf
          style: normal
        - asset: assets/fonts/OnestMedium.ttf
          weight: 500
        - asset: assets/fonts/OnestBold.ttf
          weight: 700
        - asset: assets/fonts/OnestExtraBold.ttf
          weight: 800
